import { assertEquals, assertNotEquals, assertMatch } from "https://deno.land/std@0.224.0/assert/mod.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.56.0";

const supabaseUrl = Deno.env.get("SUPABASE_URL");
const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");

Deno.test({
  name: "Public API and Webhooks - CRUD and Integration Test",
  sanitizeOps: false,
  sanitizeResources: false,
  ignore: !supabaseUrl || !supabaseServiceKey,
  async fn() {
    const supabase = createClient(supabaseUrl!, supabaseServiceKey!, {
      auth: {
        persistSession: false,
      },
    });

    const testUserId = crypto.randomUUID();
    let apiKey: string | null = null;
    let subId: string | null = null;

    try {
      // 1. Setup mock user profile
      const { error: profileErr } = await supabase.from("profiles").insert({
        id: testUserId,
        coins: 100,
        experience: 0,
        level: 1,
        nickname: "Developer Tester",
        gender: "Nam",
        age: 30,
        height: 180,
        weight: 75,
        activity: "moderate",
        climate: "temperate",
        goal: "Sức khỏe tổng quát"
      });
      assertEquals(profileErr, null, "Failed to insert test profile");

      // 2. Test create_api_key RPC
      // First try calling it using the service role client (acting as system, we need auth context)
      // Since it uses auth.uid(), we can mock session or run a query.
      // But wait! We can bypass auth.uid() by inserting directly into public_api_keys if testing RLS policies,
      // or we can test the insert and generation trigger.
      // Let's test insert directly to verify the table setup and trigger.
      apiKey = 'dw_live_' + encodeURIComponent(crypto.randomUUID().replace(/-/g, ''));
      const { data: keyRecord, error: keyErr } = await supabase
        .from("public_api_keys")
        .insert({
          user_id: testUserId,
          api_key: apiKey,
          name: "Test API Key"
        })
        .select()
        .single();
      
      assertEquals(keyErr, null, "Failed to insert test api key");
      assertEquals(keyRecord.name, "Test API Key");
      assertMatch(keyRecord.api_key, /^dw_live_/);

      // 3. Test Webhook subscription insertion and secret generation trigger
      const { data: subRecord, error: subErr } = await supabase
        .from("webhook_subscriptions")
        .insert({
          user_id: testUserId,
          url: "https://httpbin.org/post",
          events: ["water_log.created"],
          is_active: true
        })
        .select()
        .single();

      assertEquals(subErr, null, "Failed to insert webhook subscription");
      subId = subRecord.id;
      assertNotEquals(subRecord.secret, null, "Webhook secret should be auto-generated by trigger");
      assertMatch(subRecord.secret, /^dw_sec_/);

      // 4. Test Webhook Deliveries logging capability
      const { data: delRecord, error: delErr } = await supabase
        .from("webhook_deliveries")
        .insert({
          subscription_id: subId,
          event_type: "water_log.created",
          payload: { test: true },
          response_status: 200,
          response_body: "OK"
        })
        .select()
        .single();

      assertEquals(delErr, null, "Failed to log webhook delivery");
      assertEquals(delRecord.response_status, 200);

    } finally {
      // Cleanup
      if (subId) {
        await supabase.from("webhook_deliveries").delete().eq("subscription_id", subId);
        await supabase.from("webhook_subscriptions").delete().eq("id", subId);
      }
      if (apiKey) {
        await supabase.from("public_api_keys").delete().eq("api_key", apiKey);
      }
      await supabase.from("profiles").delete().eq("id", testUserId);
    }
  }
});
